// <auto-generated />
using System;
using System.Reflection.Emit;
using Ntwalo_APPR6312.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ntwalo_APPR6312.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241001204542 _AddUserName2")]
    partial class AddUserName2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ntwalo_APPR6312.Models.ApplicationUser", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                b.Property<string>("Password")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserEmail")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserName")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId");

                b.ToTable("ApplicationUsers");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.Catagory", b =>
            {
                b.Property<int>("CatagoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatagoryId"));

                b.Property<string>("CatagoryName")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CatagoryId");

                b.ToTable("Catagories");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.Disaster", b =>
            {
                b.Property<int>("DisasterId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisasterId"));

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Location")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("DisasterId");

                b.ToTable("Disasters");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.DonationItem", b =>
            {
                b.Property<int>("ItemDonationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemDonationId"));

                b.Property<int>("CatagoryID")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DisasterId")
                    .HasColumnType("int");

                b.Property<DateTime>("DonationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Donor")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("numItems")
                    .HasColumnType("int");

                b.HasKey("ItemDonationId");

                b.HasIndex("CatagoryID");

                b.HasIndex("DisasterId");

                b.ToTable("DonationsItems");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.DonationMoney", b =>
            {
                b.Property<int>("DonationMoneyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationMoneyId"));

                b.Property<double>("Amount")
                    .HasColumnType("float");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<int>("DisasterId")
                    .HasColumnType("int");

                b.Property<string>("Doner")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("DonationMoneyId");

                b.HasIndex("DisasterId");

                b.ToTable("DonationsMoney");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.DonationItem", b =>
            {
                b.HasOne("Ntwalo_APPR6312.Models.Catagory", "Catagory")
                    .WithMany()
                    .HasForeignKey("CatagoryID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Ntwalo_APPR6312.Models.Disaster", "Disaster")
                    .WithMany()
                    .HasForeignKey("DisasterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Catagory");

                b.Navigation("Disaster");
            });

            modelBuilder.Entity("Ntwalo_APPR6312.Models.DonationMoney", b =>
            {
                b.HasOne("Ntwalo_APPR6312.Models.Disaster", "Disaster")
                    .WithMany()
                    .HasForeignKey("DisasterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Disaster");
            });
#pragma warning restore 612, 618
        }
    }
}
